### ISSUE TITLE
Code fields add "name" to div tag

### ISSUE THREAD

**Issue by ghost** [jan-vince/smallcontactform#105] opened 2020-09-03 22:05 UTC
If you use the new code fields (which are great by the way), the contact form adds a "name" attribute to a div tag which will generate html errors if you validate your code.

Example image attached
![Screen Shot 2020-09-03 at 4 04 14 PM](https://user-images.githubusercontent.com/40217874/92178184-3af80e80-edff-11ea-836c-fd05cd42302d.png)

**Comment by jan-vince** [comment] 2020-09-04 06:46
Hi @bmcwilliams and thanks you noticed this (the problem is with *Custom content* field, *Custom code* is fine).

It is fixed in a new version.

Best regards :)

Jan

**Closed as completed by jan-vince** 2020-09-04 06:46 UTC
